### ISSUE TITLE
Taking files from local directory

### ISSUE THREAD

**Issue by anaigmo** [oeg-upm/morph-csv#6]
I'm having some problems when I try to run the program when taking certain CSVs I store in local, but not when they are downloaded (the ones in [this repository](https://github.com/anaigmo/Bio2RDF/tree/master/data/taxonomy)). The error is as follows:

```
[main] INFO es.upm.fi.dia.oeg.model.Dataset  - Loading the CSV source files
[main] INFO es.upm.fi.dia.oeg.Morphcsv  - Generating the schema of the RDB
[main] INFO es.upm.fi.dia.oeg.rdb.RDBGenerator  - Normalizing to FN1 the CSV files
Exception in thread "main" java.lang.NullPointerException
	at es.upm.fi.dia.oeg.rdb.CSVUtils.putNull(CSVUtils.java:117)
	at es.upm.fi.dia.oeg.rdb.RDBGenerator.normalize(RDBGenerator.java:74)
	at es.upm.fi.dia.oeg.rdb.RDBGenerator.generateSchemaRDB(RDBGenerator.java:34)
	at es.upm.fi.dia.oeg.Morphcsv.main(Morphcsv.java:58)
```

**Comment by dachafra** [comment]
Can you share the config file please?

**Comment by dachafra** [comment]
Solved
